// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../express

import * as express from 'express';
import { Router } from 'express';

export class AuthenticatedRoute {
    constructor(routePrefix: string, router: express.Router, authHandler?: any);
    get(handler: any): this;
    post(handler: any): this;
    put(handler: any): this;
    delete(handler: any): this;
}
export class AuthenticatedRouter {
    router: Router;
    constructor(authHandler?: any);
    route(route: string): AuthenticatedRoute;
}

